name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Run app
      run: python app.py
    - name: Build Docker image
      run: docker build -t mini-project-lpu-1 .
    # ...existing code...
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest ruff
    - name: Lint with Ruff
      run: ruff .
    - name: Run tests
      run: pytest
# ...existing code...